const express = require('express')
const router = express.Router()
const eleveController = require('../../controllers/actions/eleveController')
router.post('/ajouterEleve',eleveController.AjouterEleve)
router.get('/listeEleve/:idAs',eleveController.ListeEleve)
router.post('/modifierEleve',eleveController.ModifierEleve)
router.get('/listeEleveInscrit/:idAs',eleveController.ListeEleveInscrit)
router.post('/rechercheEleveInscrits',eleveController.RechercheEleveInscrits)
router.get('/listeEnfantProfesseur',eleveController.ListeEnfantProfesseur)
router.get('/listeParClasse/:idAs/:idClasse',eleveController.ListeParClasse)
router.get('/ficheReinscripion/:numMatricule/:idAs',eleveController.FicheReinscrire)
router.post('/reinscription',eleveController.Reinscription)
router.get('/detailEleve/:numMatricule',eleveController.DetailEleve)
router.get('/detailEleveInscrit/:numMatricule/:idAs',eleveController.DetailEleveInscrit)
router.post('/modifierEleveInscrit',eleveController.ModifierEleveInscrit)
router.post('/rechercheEleve',eleveController.RechercheEleve)
router.get('/tuteurEleve/:numMatricule',eleveController.TuteurEleve)
//
router.delete('/eleve/supprimer/:id',eleveController.SupprimerEleve)
router.delete('/eleveInscrit/supprimer/:idInscri',eleveController.SupprimerEleveInscrit)
router.get('/detail/liste/anneeScolaire',eleveController.As)
module.exports = router