const express = require('express')
const router = express.Router()
const professeurController = require('../../controllers/actions/professeurController')

router.post('/ajouterProfesseur',professeurController.Ajouter)
router.get('/professeur/listeClasse',professeurController.Classe)
router.get('/professeur/niveau',professeurController.Niveau)
router.post('/professeur/eleveInd',professeurController.EleveInd)
router.get('/professeur/trimestre/:idAs',professeurController.Trimestre)
router.get('/professeur/matiere',professeurController.Matiere)
router.get('/professeur/matiereClasse/:idClasse',professeurController.MatiereClasse)
router.get('/professeur/evaluation',professeurController.Evaluation)
router.post('/ajouter/noteIndividuelle',professeurController.AjouterNoteIndividuelle)
router.post('/professeur/eleveGrp',professeurController.EleveGrp)
router.get('/professeur/matiere/trimestre/:idAs',professeurController.MatiereTrimestre)
router.get('/professeur/classe/matiere/trimestre/:idProf/:idAs',professeurController.MatiereTrimestreProf)
router.get('/professeur/voirNote/:idTrimestre/:codemat',professeurController.VoirNote)
router.get('/professeur/classe/voirNote/:idProf/:idTrimestre/:codemat',professeurController.VoirNoteProf)
router.get('/professeur/afficherNoteEleve/:coefficient/:idTrimestre/:codemat/:idClasse/:idEvalua/:idAs',professeurController.AfficherNote)
router.post('/Modifier/noteGroupee',professeurController.Modifier)
router.get('/getCoefficient/:idClasse/:codemat',professeurController.getCoefficient)
router.post('/pointage/eleve',professeurController.pointageEleve)
router.post('/nouveau/absence',professeurController.nouveauAbsent)
router.post('/professeur/nombreHeureAbsence',professeurController.nombreHeureAbsence)
router.post('/professeur/detailAbsence',professeurController.detailAbsence)
router.post('/Ajouter/noteGroupee',professeurController.noteGroupee)
router.post('/envoyer/devoir',professeurController.NouveauDevoir)
router.post('/verificationNote',professeurController.VerificationNote)
router.get('/structure/enregistrementNote/:idEvalua/:idClasse/:idTrimestre/:idNiv/:codemat',professeurController.StructureEnregistrementNote)
router.get('/professeur/listeEleve/:idClasse/:idNiv/:idAs',professeurController.listeEleve)
//router.get('/professeur/rangNote/:idClasse/:idEvalua/:idTrimestre/:codemat',professeurController.RangNote)
router.get('/moyenneMatiere/classe/:coef/:idClasse/:idEvalua/:idTrimestre/:codemat/:idAs',professeurController.SommeMoyenneMatiere)
router.get('/note/plusHaut/:idClasse/:idEvalua/:idTrimestre/:codemat',professeurController.NotePlusHaut)
router.get('/note/plusBasse/:idClasse/:idEvalua/:idTrimestre/:codemat',professeurController.NotePlusBasse)

// CONSULTATION MOYENNE
router.post('/professeur/moyenneEleve',professeurController.TableauMoyenneEleve)
router.get('/professeur/tableauMoyenne/contenus/:idTrimestre/:idNiv/:idEvalua/:idClasse/:idAs',professeurController.Contenus)
router.post('/professeur/afficher/tableauMoyenne',professeurController.TableauMoyenne)
router.post('/professeur/contenus/consultationMoyenne',professeurController.contenusConsultationMoyenne)
router.post('/professeur/MoyenneGeneraleClasse',professeurController.MoyenneGeneraleClasse)
router.post('/professeur/MoyenneGeneralHaut',professeurController.MoyenneGeneralHaut)
router.post('/professeur/MoyenneGeneralBas',professeurController.MoyenneGeneralBas)
//
router.get('/professeur/liste',professeurController.listeProfs)
router.post('/professeur/fichePresence',professeurController.fichePresence)
router.post('/professeur/ajoutAbsence',professeurController.ajoutAbsence)

//
router.get('/professeur/classe/:idProf',professeurController.ProfClasse)
router.get('/professeur/matiere/:idProf',professeurController.ProfMatiere)
router.get('/professeur/matiereClasse/:idClasse/:idProf',professeurController.ProfMatiereClasse)
//
router.get('/professeur/noteDuplicate/:idClasse/:idEvalua/:idTrimestre/:codemat',professeurController.NoteDuplicate)
router.post('/professeur/moyenneDuplicate',professeurController.MoyenneDuplicate)
router.get('/professeur/editer/note/plusInfo/:idClasse/:idTrimestre/:codemat/:idEvalua',professeurController.PlusInfosDetailNote)
router.get('/professeur/editer/noteEleve/:idClasse/:idTrimestre/:codemat/:idEvalua/:idAs',professeurController.EditerNoteEleve)
router.delete('/professeur/supprimer/passerEvaluation/:idEvalua/:idClasse/:idTrimestre',professeurController.SupprimerEvaluation)
//
router.get('/tableProfesseur',professeurController.ListeProfesseur)
router.post('/rechercheProfesseur',professeurController.RechercheProf)
router.post('/modifierProfesseur',professeurController.ModifierProfesseur)
router.delete('/professeur/effacer/:idProf',professeurController.SupprimerProfesseur)
module.exports = router

